# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#


development:
  adapter: postgresql
  encoding: unicode
  database: todo_list_development
  pool: 5
  username: sergey
  password: 111

test:
  adapter: postgresql
  encoding: unicode
  database: todo_list_test
  pool: 5
  username: todo_list
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: todo_list_production
  pool: 5
  username: todo_list
  password:
